### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by sarathbp** [vahegrigoryan/reschedule-us-visa#1]
Can Run this windows PC?

I am not computer person. excuse me if its a dumb question

**Comment by vahegrigoryan** [comment]
Yes, the only requirement is that you need to have Node version >=14 installed on your machine to run this.
After you download and install [Node](https://nodejs.org/en/download), just follow steps described in the README and you'll be able to run it

**Comment by sarathbp** [comment]
will it work for group appointment ?
![image](https://user-images.githubusercontent.com/125307573/227695512-c872ae51-63aa-4dc2-af05-b1e881d79523.png)

**Comment by vahegrigoryan** [comment]
Sorry for late response @sarathbp . In the last update it works for the group appointment as well. You just need to set the HAS_MULTIPLE_APPLICANTS environment variable to true
